### PR TITLE
fix out of bound when sending read receipt

### LINKED ISSUE #386: UnreadBadge issues
After reading the latest messages, the UnreadBadge may still be displayed at times
           
https://github.com/user-attachments/assets/3885cb5e-1c9f-4503-9aa7-8055c2abad40

### PR DESCRIPTION
**Pull request by alanpoon**
Fixes #386

### CODE REVIEW

File: src/home/room_screen.rs [hunk 1]
```diff
@@ -2442,7 +2442,13 @@ impl RoomScreen {
...
                     let Some((last_event_id, last_timestamp)) = tl_state
                         .items
-                        .get(first_index + portal_list.visible_items())
+                        .get(
+                            if first_index + portal_list.visible_items() >= tl_state.items.len() {
+                                tl_state.items.len() - 1
+                            } else {
+                                first_index + portal_list.visible_items()
+                            },
+                        )
```
Comment (kevinaboos) [inline src/home/room_screen.rs:2451]: this is a simple `min` operation. Also, avoid subtraction overflow.
```suggestion
                        .get(std::cmp::min(
                            first_index + portal_list.visible_items(),
                            tl_state.items.len().saturating_sub(1)
                        ))
```

**Review by kevinaboos — APPROVED** [review]
nice catch, thanks! There are some improvements to be made on your fixes though, see my comment.

**Review by kevinaboos — APPROVED** [review]
